spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/smart_agriculture
spring.datasource.username=root
spring.datasource.password=HARINI

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
weather.api.key=5fc0fcc3ec2921efa9fd8b2d80c60b84